services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  mycourse-api:
    container_name: mycourse-db-api
    image: ibrahimiba/mycourse-api
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/custumer
    networks:
      - db
    ports:
      - "8088:8080"
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: